INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Hollywood', '46', '23', 'Hollywood', '1971-12-31', 'gmail@gmail.com', 'Sergeevich', 'John', 'Barrymore');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Dublin', '34', '43', 'Dublin', '1992-12-31', 'mail@yandex.com', 'Polikarpovich', 'Brendan', 'Behan');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('New York', '64', '54', 'York', '1993-12-31', 'mail@gmail.com', 'Sergeevich', 'Bix', 'Beiderbecke');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('London', '234', '65', 'London', '1980-12-31', 'gmail@yandex.com', 'Polikarpovich', 'George', 'Best');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Windsor', '75', '76', 'Dublin', '1921-12-31', 'yandex@mail.com', 'Sergeevich', 'John', 'Bonham');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('New York City', '23', '86', 'Street', '1932-12-31', 'yandex@gmail.com', 'Polikarpovich', 'Julia', 'Bruns');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Pittsburgh', '64', '45', 'Street', '1963-12-31', 'mail@yandex.com', 'Andreevich', 'Rob', 'Buck');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Geneva', '34', '34', 'London', '1923-12-31', 'gmail@gmail.com', 'Sergeevich', 'Richard', 'Burton');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Reading', '75', '54', 'Street', '1967-12-31', 'yandex@yandex.com', 'Polikarpovich', 'David', 'Byron');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Los Angeles', '34', '64', 'London', '1964-12-31', 'mail@gmail.com', 'Sergeevich', 'Truman', 'Capote');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Stockholm', '75', '23', 'Street', '1975-12-31', 'mail@yandex.com', 'Andreevich', 'Torsten', 'Carleman');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Boston', '34', '43', 'Dublin', '1925-12-31', 'yandex@gmail.com', 'Polikarpovich', 'Leonard', 'Chadwick');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('La Jolla', '54', '64', 'London', '1998-12-31', 'mail@gmail.com', 'Andreevich', 'Raymond', 'Chandler');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Treasure Island', '65', '34', 'London', '1940-12-31', 'mail@gmail.com', 'Sergeevich', 'Michael', 'Clarke');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Muhos', '34', '75', 'London', '1975-12-31', 'mail@yandex.com', 'Andreevich', 'Miika', 'Tenkula');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Slough', '65', '23', 'Street', '1987-12-31', 'gmail@mail.com', 'Polikarpovich', 'Brian', 'Connolly');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('London', '23', '432', 'Dublin', '1934-12-31', 'gmail@yandex.com', 'Andreevich', 'Peter', 'Cook');
INSERT INTO contact (city, flat, home, street, date_of_birth, email, middle_name, name, surname) VALUES ('Pasadena', '665', '432', 'Street', '1974-12-31', 'mail@mail.com', 'Sergeevich', 'Michael', 'Elphick');

INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ADMINISTRATOR', 'admin', '1');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'SUPERVISOR', 'user1', '2');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ORDER_MANAGER', 'user2', '3');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'PROCESSING_MANAGER', 'user3', '4');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'COURIER', 'user4', '5');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ADMINISTRATOR', 'user5', '6');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'SUPERVISOR', 'user6', '7');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ORDER_MANAGER', 'user7', '8');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'PROCESSING_MANAGER', 'user8', '9');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'COURIER', 'user9', '10');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ADMINISTRATOR', 'user10', '11');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'SUPERVISOR', 'user11', '12');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ORDER_MANAGER', 'user12', '13');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'PROCESSING_MANAGER', 'user13', '14');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'COURIER', 'user14', '15');
INSERT INTO user (password, role, username, contact_id) VALUES ('1234', 'ADMINISTRATOR', 'user15', '16');

INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('22510', '1990-12-2', 'no', 'NEW', '1', '5', '4', '3', '1');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('25032', '1990-12-1', 'no', 'ACCEPTED', '2', '10', '9', '8', '2');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('15120', '1990-12-4', 'no', 'IN_PROCESSING', '3', '15', '4', '3', '3');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('30320', '1990-12-2', 'no', 'READY_FOR_DELIVERY', '4', '10', '9', '8', '4');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('43343', '1990-12-5', 'no', 'DELIVERY', '5', '5', '4', '3', '1');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('22510', '1990-12-2', 'no', 'CAN_NOT_BE_EXECUTED', '6', '10', '9', '8', '5');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('25032', '1990-12-1', 'no', 'CANCELED', '7', '15', '4', '3', '6');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('15120', '1990-12-4', 'no', 'CLOSED', '8', '10', '9', '8', '7');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('22510', '1990-12-2', 'no', 'NEW', '1', '5', '4', '3', '8');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('25032', '1990-12-1', 'no', 'ACCEPTED', '2', '10', '9', '8', '9');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('15120', '1990-12-4', 'no', 'IN_PROCESSING', '3', '15', '4', '3', '10');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('30320', '1990-12-2', 'no', 'READY_FOR_DELIVERY', '4', '10', '9', '8', '11');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('43343', '1990-12-5', 'no', 'DELIVERY', '5', '5', '4', '3', '1');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('22510', '1990-12-2', 'no', 'CAN_NOT_BE_EXECUTED', '6', '10', '9', '8', '12');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('25032', '1990-12-1', 'no', 'CANCELED', '7', '15', '4', '3', '13');
INSERT INTO orders (cost, date, description, state, customer_id, delivery_manager_id, processing_manager_id, reception_manager_id, recipient_id) VALUES ('15120', '1990-12-4', 'no', 'CLOSED', '8', '10', '9', '8', '14');

INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone1', '234', '4445887', '33', 'HOME', '1');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone2', '123', '4444287', '23', 'MOBILE', '2');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone3', '123', '4215887', '33', 'HOME', '3');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone4', '433', '4432887', '23', 'MOBILE', '4');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone5', '543', '4444387', '33', 'HOME', '5');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone1', '234', '4445887', '33', 'HOME', '6');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone2', '123', '4444287', '23', 'MOBILE', '7');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone3', '123', '4215887', '33', 'HOME', '8');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone4', '433', '4432887', '23', 'MOBILE', '9');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone5', '543', '4444387', '33', 'HOME', '10');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone1', '234', '4445887', '33', 'HOME', '11');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone2', '123', '4444287', '23', 'MOBILE', '12');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone3', '123', '4215887', '33', 'HOME', '13');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone4', '433', '4432887', '23', 'MOBILE', '14');
INSERT INTO phone (comment, country_code, number, operator_code, type, owner_id) VALUES ('phone5', '543', '4444387', '33', 'HOME', '15');

INSERT INTO order_change (comment, date, new_state, order_id, user_changed_status_id) VALUES ('no', '1990-12-31', 'NEW', '1', '1');
INSERT INTO order_change (comment, date, new_state, order_id, user_changed_status_id) VALUES ('no', '1990-12-31', 'NEW', '1', '1');
INSERT INTO order_change (comment, date, new_state, order_id, user_changed_status_id) VALUES ('no', '1990-12-31', 'NEW', '1', '1');
INSERT INTO order_change (comment, date, new_state, order_id, user_changed_status_id) VALUES ('no', '1990-12-31', 'NEW', '1', '1');
INSERT INTO order_change (comment, date, new_state, order_id, user_changed_status_id) VALUES ('no', '1990-12-31', 'NEW', '1', '1');